name: CI/CD Pipeline

on:
  push:
    branches: [ main, sit, uat ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, sit, uat ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'sit'
        type: choice
        options:
          - sit
          - uat
          - prod
      image_tag:
        description: 'Specific image tag to deploy'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: conan_test
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean verify -B
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/conan_test
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: admin
          SPRING_FLYWAY_URL: jdbc:postgresql://localhost:5432/conan_test
          SPRING_FLYWAY_USER: admin
          SPRING_FLYWAY_PASSWORD: admin

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            target/site/jacoco
            target/site/surefire-reports
            target/site/unit-tests-report.html
            target/site/integration-tests-report.html

#      - name: SonarCloud Scan
#        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=happiness-coding_conan

  build-and-push-image:
    name: Build and Push Docker image
    needs: build-and-test
    # Only build images for SIT branch and version tags
    if: |
      needs.build-and-test.result == 'success' && 
      github.event_name != 'pull_request' && 
      (github.ref == 'refs/heads/sit' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_image_tag.outputs.tag }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: set_image_tag
        run: |
          # Check if this is a tag build (release)
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            # Use the version from the tag (vX.Y.Z -> X.Y.Z)
            TAG="${GITHUB_REF#refs/tags/v}"
            echo "Using release tag: $TAG"
          else
            # For SIT branch, use timestamp and short commit hash
            SHORT_SHA=$(git rev-parse --short HEAD)
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            TAG="sit-${TIMESTAMP}-${SHORT_SHA}"
            echo "Using SIT build tag: $TAG"
          fi
          
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          
          # Also store it for other jobs
          mkdir -p ./artifacts
          echo "${TAG}" > ./artifacts/image-tag.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.set_image_tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: ./artifacts/image-tag.txt
          retention-days: 90

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.set_image_tag.outputs.tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      # Add a step to create a GitHub issue with the newly built image tag
      - name: Create notification issue
        if: github.ref == 'refs/heads/sit'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = "${{ steps.set_image_tag.outputs.tag }}";
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `New image built for SIT: ${tag}`,
              body: `A new image has been built and is ready for testing in SIT environment.
            
              **Image Tag:** \`${tag}\`
              **Built from commit:** [${process.env.GITHUB_SHA.substring(0,7)}](https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${process.env.GITHUB_SHA})
              **Built at:** ${new Date().toISOString()}
            
              To promote this image to UAT after testing:
              1. Go to Actions -> CI/CD Pipeline -> "Run workflow"
              2. Select:
                 - Branch: \`uat\`
                 - Environment: \`uat\`
                 - Image tag: \`${tag}\`
            
              [Run workflow](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/workflows/ci-cd.yml)`
            });

  deploy-to-sit:
    name: Deploy to SIT
    needs: [build-and-test, build-and-push-image]
    if: |
      always() && 
      needs.build-and-test.result == 'success' && 
      (
        (github.event_name == 'push' && github.ref == 'refs/heads/sit') || 
        (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'sit')
      )
    runs-on: ubuntu-latest
    environment:
      name: sit
      url: https://sit.conan.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get image tag
        id: get_image_tag
        run: |
          # Use manually specified tag if provided
          if [[ -n "${{ github.event.inputs.image_tag }}" ]]; then
            echo "tag=${{ github.event.inputs.image_tag }}" >> $GITHUB_OUTPUT
            echo "Using manually specified tag: ${{ github.event.inputs.image_tag }}"
          else
            # Otherwise use the tag from the build job
            echo "tag=${{ needs.build-and-push-image.outputs.image_tag }}" >> $GITHUB_OUTPUT
            echo "Using build job tag: ${{ needs.build-and-push-image.outputs.image_tag }}"
          fi

      - name: Update Kubernetes manifests
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ steps.get_image_tag.outputs.tag }}
        run: |
          echo "Updating manifests for SIT environment with image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
          sed -i "s|image: .*|image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}|g" k8s/overlays/sit/deployment.yaml

      - name: Commit and push updated manifests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s/overlays/sit/deployment.yaml
          git commit -m "Update SIT deployment to use image tag ${IMAGE_TAG}"
          git push

  deploy-to-uat:
    name: Deploy to UAT
    needs: [build-and-test]
    if: |
      always() && 
      needs.build-and-test.result == 'success' && 
      github.event_name == 'workflow_dispatch' && 
      github.event.inputs.environment == 'uat'
    runs-on: ubuntu-latest
    environment:
      name: uat
      url: https://uat.conan.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifests
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          echo "Updating manifests for UAT environment with image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
          sed -i "s|image: .*|image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}|g" k8s/overlays/uat/deployment.yaml

      - name: Commit and push updated manifests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s/overlays/uat/deployment.yaml
          git commit -m "Update UAT deployment to use image tag ${IMAGE_TAG}"
          git push

  deploy-to-prod:
    name: Deploy to Production
    needs: [build-and-test]
    if: |
      always() && 
      needs.build-and-test.result == 'success' && 
      github.event_name == 'workflow_dispatch' && 
      github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://conan.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes manifests
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          echo "Updating manifests for Production environment with image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
          sed -i "s|image: .*|image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}|g" k8s/overlays/prod/deployment.yaml

      - name: Commit and push updated manifests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s/overlays/prod/deployment.yaml
          git commit -m "Update Production deployment to use image tag ${IMAGE_TAG}"
          git push